### ISSUE TITLE
Not working with 3ds Max 2019

### ISSUE THREAD

**Issue by AmonBune** [Makiah/BotW-SBFRES-to-FBX#4]
It seems that the Python extraction script doesn't work with 3ds Max 2019.
When executing the MAXScript it throws the error "-- Unable to convert: undefined to type: Integer64"
This happens everytime the CompleteAutomation.py calls the MAXScript.

![capture](https://user-images.githubusercontent.com/15927695/38234363-f3eda094-371d-11e8-8425-0824f216403c.PNG)

**Comment by Makiah** [comment]
That's unfortunate, but it seems that newer versions of Max don't work with RTB's extraction script.  I personally recommend the 2015 version (I think I include a link in the README).  It's possible that he's been able to fix those bugs in newer versions of the core extraction script, but I don't have time to update it (a PR would be great though if you know how!)

**Comment by AmonBune** [comment]
@Makiah Yes, the README mentions that 3ds Max 2015 is recommended, but there is no download link for a trial or something similar. And it's also not obtainable through the official 3ds Max website. The only way get it is through some suspicious torrents.

**Comment by AmonBune** [comment]
Just a note: The same issue happens in 3ds Max 2016 as well. So failing versions are probably 2016, 2017, 2018 and 2019.

**Comment by Makiah** [comment]
Hmmm, I have to admit that I'm not sure how to fix this, as I think it would require an overhaul of RTB's script, and I'll need to re-install Parallels to attempt a fix.  I'll look into it, but I suspect that the only way to use the script effectively will be via 2015 or perhaps a bit older.

**Comment by Makiah** [comment]
@AmonBune The update I just pushed uses a modded version of RTB's latest script and 3DS Max 2016 works with it (so it can be downloaded from Autodesk's site).  2019 might work but I doubt it.

**Comment by Thisdidnotwork** [comment]
Hey, this still doesn't seem to be working I downgraded to the 2016 version and while it works for a few, but I get that error on the same files, I've downloaded the files again today and everything I've tried hasn't worked. Do you need to see what my files look like?

**Comment by Makiah** [comment]
I got that error a couple times while I was debugging, and it turned out to be because my game files had whitespace in the path leading up to them.  Check your path for any such spaces: for example, mine changed from "C:\Users\makiah\Desktop\Zelda Files" to "C:\Users\makiah\Desktop\ZeldaFiles".  If you don't see any, copy and paste the first line of the `fbxextraction/BFRES to FBX 2.ms` script (the one that is preceded by `USER_WORKSPACE_PATH =`) into this thread.

**Comment by Thisdidnotwork** [comment]
There were spaces, but I did alter them and ran the script and encountered the same error.

E:\\Projects\\Zeldas_Ballad_Project\\BotW-SBFRES-to-FBX-master\\fbxextraction\\Workspace\\

Is this the line you wanted?

**Comment by Makiah** [comment]
Huh, that's odd.  Try renaming those folders so that the path is `E:\Projects\ZeldasBalladProject\BotWSBFREStoFBXmaster\fbxextraction\Workspace\`, and then replace the first line of `fbxextraction/BFRES to FBX 2.ms` with `USER_WORKSPACE_PATH = E:\\Projects\\ZeldasBalladProject\\BotWSBFREStoFBXmaster\\fbxextraction\Workspace\\`

**Comment by Thisdidnotwork** [comment]
The removal of spaces doesn't seem to be doing anything.

**Comment by Thisdidnotwork** [comment]
Removing spaces doesn't seem to do anything. what is Integar64 even referring to?

![capture](https://user-images.githubusercontent.com/42131466/43736191-bed73a6c-998a-11e8-8992-cc60896c0235.PNG)

**Comment by Makiah** [comment]
Huh idk then, maybe your game files are corrupted somehow.  As for what that error means...  ¯\_(ツ)_/¯ I have no idea.  I didn't write the MAXScript, I just slightly modified it to automatically extract and export everything.

**Comment by Thisdidnotwork** [comment]
I can figure out to get those another way, is there a way to make it skip to the next one if it encounters that error? There are files this that this process works for, but this error halts the process until I close the program.

**Comment by Makiah** [comment]
Which file is this happening for specifically?  You can skip it by adding a folder in `fbxextraction/Database` with the SBFRES's name, since the script checks to see if they're already extracted and will think that it already has been if it sees a folder with the model's name.

**Comment by Thisdidnotwork** [comment]
After a bit of snooping there are simply some BFRES files that the script does not unpack, and it is these that the error was occurring. So I used your method to skip them since they were usually ones I didn't need.
